import type {Metadata} from "next";

import {Inter} from "next/font/google";

import "@/styles/globals.css";

import {cn} from "@/lib/utils";
import {ThemeProvider} from "@/components/theme-provider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Nextjs Starter",
  description: "Generated by Guillermo Uzner",
};

interface RootLayoutProps {
  conversor: React.ReactNode;
  data: React.ReactNode;
}

export default function RootLayout({conversor, data}: RootLayoutProps) {
  return (
    <html suppressHydrationWarning lang="es">
      <head />
      <body className={cn("min-h-screen bg-background font-sans antialiased", inter.variable)}>
        <ThemeProvider enableSystem attribute="class" defaultTheme="dark">
          <section className="mx-4 grid h-screen grid-cols-1 gap-10 lg:grid-cols-2">
            <div className="col-span-1 border text-center">{conversor}</div>
            <div className="col-span-1 border text-center">{data}</div>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
